name: C/C++ CI linux

on: [push]

jobs:
  build:
    strategy:
      matrix:
        buildtype: [Debug, Release]

    runs-on: ubuntu-latest
    
    steps:
    - name: Remove unnecessary directories to free up space
      run: |
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet

    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow --tags

    - name: pkg
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends g++ autoconf automake libtool xz-utils libasound2-dev libpulse-dev libgtk-3-dev cmake p7zip-full

    - name: depot_tools
      run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH

    - name: fetch webrtc
      run: |
          mkdir webrtc
          pushd webrtc
          fetch --nohooks webrtc
          popd

    - name: build
      run: |
          export CONFIGURE_ARGS="--disable-x86asm --disable-asm --arch=arm --enable-cross-compile --target-os=linux --enable-pic --cc=clang --cxx=clang++ --ld=clang"

          export PATH=$(pwd)/webrtc/src/third_party/llvm-build/Release+Asserts/bin:$PATH
          sudo apt-get install -y binutils-arm-linux-gnueabihf gcc-arm-linux-gnueabihf

          # 新增：创建配置日志目录
          mkdir -p webrtc/src/third_party/ffmpeg/ffbuild

          (cd webrtc/src/third_party/ffmpeg && ./configure ${CONFIGURE_ARGS} ) 2>&1  # 确保日志输出

          # 带完整工具链配置
          cmake \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_AR=llvm-ar \
          -DCMAKE_SYSROOT=$(pwd)/webrtc/src/build/linux/debian_bullseye_arm-sysroot \
          -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} .
          make


    - name: cpack 
      run: | 
          rm -f *.tar.gz
          cpack
          echo "artifactPath=$(ls *.tar.gz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifactPath }}
        path: ${{ env.artifactPath }}   

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.artifactPath }}