name: C/C++ CI linux

on: [push]

jobs:
  build:
    strategy:
      matrix:
        buildtype: [Debug, Release]

    runs-on: ubuntu-latest
    
    steps:
    - name: Remove unnecessary directories to free up space
      run: |
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet

    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow --tags

    - name: pkg
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends g++ autoconf automake libtool xz-utils libasound2-dev libpulse-dev libgtk-3-dev cmake p7zip-full

    - name: depot_tools
      run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH
      
    - name: fetch webrtc
      run: |
          mkdir webrtc
          pushd webrtc
          fetch --nohooks webrtc
          popd     
          
          # 安装ARM交叉编译基础库
          sudo apt-get install -y libc6-dev-armhf-cross libgcc-10-dev-armhf-cross libstdc++-10-dev-armhf-cross

          # 创建sysroot目录结构
          sudo mkdir -p ${PWD}/webrtc/src/build/linux/debian_bullseye_arm-sysroot/usr/lib/arm-linux-gnueabihf
          
          # 链接关键库文件
          sudo ln -s /usr/arm-linux-gnueabihf/lib ${PWD}/webrtc/src/build/linux/debian_bullseye_arm-sysroot/usr/lib/arm-linux-gnueabihf
          sudo ln -s /usr/lib/gcc-cross/arm-linux-gnueabihf/10 ${PWD}/webrtc/src/build/linux/debian_bullseye_arm-sysroot/usr/lib/gcc

    - name: build
      run: |
          WORKSPACE=$(echo "${GITHUB_WORKSPACE}" | tr -d '[:space:]')
          cd "${WORKSPACE}"

          export CONFIGURE_ARGS="--disable-x86asm --disable-asm --arch=arm --enable-cross-compile --target-os=linux --enable-pic --cc=clang --cxx=clang++ --ld=clang"
          export PATH=$(pwd)/webrtc/src/third_party/llvm-build/Release+Asserts/bin:$PATH
          sudo apt-get install -y binutils-arm-linux-gnueabihf gcc-arm-linux-gnueabihf

           # 更新工具链参数
          export CLANG_FLAGS="--target=arm-linux-gnueabihf --sysroot=${WORKSPACE}/webrtc/src/build/linux/debian_bullseye_arm-sysroot -B${WORKSPACE}/webrtc/src/build/linux/debian_bullseye_arm-sysroot/usr/lib/gcc -march=armv7-a -mfpu=neon -mfloat-abi=hard"

          # 新增：创建配置日志目录
          mkdir -p webrtc/src/third_party/ffmpeg/ffbuild

          (cd webrtc/src/third_party/ffmpeg && ./configure ${CONFIGURE_ARGS} ) 2>&1  # 确保日志输出

          # 带完整工具链配置
          cmake -B "${WORKSPACE}/build" -S "${WORKSPACE}" \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_C_FLAGS="${CLANG_FLAGS}" \
          -DCMAKE_CXX_FLAGS="${CLANG_FLAGS}" \
          -DCMAKE_SYSROOT=${PWD}/webrtc/src/build/linux/debian_bullseye_arm-sysroot \
          -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -Wl,--sysroot=${PWD}/webrtc/src/build/linux/debian_bullseye_arm-sysroot" \
          -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \  # 跳过链接测试
          -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} \
          --no-warn-unused-cli

          cmake --build "${WORKSPACE}/build" --verbose
          


    - name: cpack 
      run: | 
          rm -f *.tar.gz
          cpack
          echo "artifactPath=$(ls *.tar.gz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifactPath }}
        path: ${{ env.artifactPath }}   

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.artifactPath }}