name: Deploy docker

on: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Remove unnecessary directories to free up space
      run: |
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
       
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow --tags

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push devcontainer
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        target: builder
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}-dev 

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }} 

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: ${{ steps.meta.outputs.json != '' && fromJSON(steps.meta.outputs.json).tags[0] || '' }}
        containerAppName: webrtcstreamer
        resourceGroup: deploy
        targetPort: 8000
